#!/bin/bash
if [ -z $VMVIEW_SERVERURL ]; then
	VMSERVER="10.12.9.103"
else
	VMSERVER=$VMVIEW_SERVERURL
fi
ARGS="--once --serverURL $VMSERVER -q"
if [ "X$VMVIEW_OPTIONS" != "X" ]; then
	ARGS="$ARGS $VMVIEW_OPTIONS"
fi
export USER=localuser
#export VMWARE_DISABLE_PULSE_AUDIO_SUPPORT=1
/usr/bin/vmware-view $ARGS
