#!/bin/bash
if [ -z $VMVIEW_SERVERURL ]; then
	VMSERVER="10.11.201.1"
else
	VMSERVER=$VMVIEW_SERVERURL
fi
ARGS="--once --serverURL $VMSERVER"
if [ "X$VMVIEW_OPTIONS" != "X" ]; then
	ARGS="$ARGS $VMVIEW_OPTIONS"
fi
export USER=root
export VMWARE_DISABLE_PULSE_AUDIO_SUPPORT=1
/usr/bin/vmware-view $ARGS
